export const LoginConstant={
    
        LOGIN_REQUEST:"LOGIN_REQUEST",
        LOGIN_SUCCESS:"LOGIN_SUCCESS",
        LOGIN_FAIL:"LOGIN_FAIL",
        SAGA_LOGIN_SUCCESS:"SAGA_LOGIN_SUCCESS",
        SAGA_LOGIN_REQUEST:"SAGA_LOGIN_REQUEST",
        SAGA_LOGIN_FAIL:"SAGA_LOGIN_FAIL"
    
}

export const LogoutConstant={
    
        LOGOUT_REQUEST:"LOGOUT_REQUEST",
        LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
        LOGOUT_FAIL:"LOGOUT_FAIL",
        
}